apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: IMAGE_BACKEND   # <-- placeholder replaced in pipeline
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets
