apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: "nginx"   # or "nginx" if using ingress-nginx 
spec:
  rules:
  - host: piyush-web-app.co.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
